# Generated by Django 5.0.4 on 2024-04-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_ch', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_id', models.SmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_publish', models.BooleanField(default=True)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('internal_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ch', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional', models.ManyToManyField(blank=True, related_name='additionals', to='restaurant.food')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.foodcategory')),
            ],
        ),
    ]
