# Generated by Django 5.0.4 on 2024-04-25 05:38

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['name_ru', 'order_id'], 'verbose_name': 'Раздел меню', 'verbose_name_plural': 'Разделы меню'},
        ),
        migrations.AddField(
            model_name='food',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='food',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='food',
            name='code',
            field=models.IntegerField(verbose_name='Код поставщика'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на китайском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='food',
            name='internal_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Код в приложении'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Специальное предложение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегетарианское меню'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name_ch',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на китайском'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name_ru',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='order_id',
            field=models.SmallIntegerField(blank=True, default=10, null=True),
        ),
    ]
